### ISSUE TITLE
Extension not working on most websites

### ISSUE THREAD

**Issue by gjvnq** [machawk1/warcreate#128] opened 2021-06-20 23:16 UTC
I tried using this extension on https://warcreate.com/ and it worked. However, when I try to use it on https://news.ycombinator.com it fails silently.

The console only shows:

```
content.js:100 Asynchronous image fetch
content.js:101 ALL IMAGES ARE NOT REPRESENTED HERE! CSS ONES ARE MISSING
(anonymous) @ content.js:101
content.js:11 https://news.ycombinator.com/y18.gif
content.js:13 Fetching entity
content.js:21 Normalizing
content.js:25 Image data normalized
content.js:28 Associating in JS
content.js:42 Resolving image fetch promise
content.js:11 https://news.ycombinator.com/s.gif
content.js:13 Fetching entity
content.js:21 Normalizing
content.js:25 Image data normalized
content.js:28 Associating in JS
content.js:42 Resolving image fetch promise
content.js:11 https://news.ycombinator.com/grayarrow.gif
content.js:13 Fetching entity
content.js:21 Normalizing
content.js:25 Image data normalized
content.js:28 Associating in JS
content.js:42 Resolving image fetch promise
```

That test was ran on incognito mode with no other extensions and the console was set to include all messages (including verbose).

On some websites (like GitHub) I sometimes see the following message on the console:

```
content.js:216 Uncaught (in promise) Error: Attempting to use a disconnected port object
    at content.js:216
(anonymous) @ content.js:216
async function (async)
(anonymous) @ content.js:172
```

**Comment by machawk1** [comment] 2021-06-28 16:33
@gjvnq Thanks for the report. I will have a look.

**Comment by machawk1** [comment] 2021-06-28 16:36
I was able to replicate this issue with the current main branch, which rules out a delta between the version on the Chrome Store and the source.

**Comment by machawk1** [comment] 2021-06-28 16:37
From source, I get this issue when trying to create a WARC from the URL supplied.

![hn](https://user-images.githubusercontent.com/2514780/123672662-958aad00-d80d-11eb-9811-60ff8272e4a3.png)

**Comment by machawk1** [comment] 2021-06-28 16:43
This seems to be caused by the markup:

```
<script type='text/javascript' src='hn.js?vbGHMem4meAJX9ahZqcC'></script></html>
```
at the very end of the HN HTML source.

The constructor for a URL object in WARCreate's warcGenerator.js:

```
parts[0] = (new window.URL(parts[0])).href
```

fails to construct the URL from "hn.js?vbGHMem4meAJX9ahZqcC". This should be caught, reported, and allow the programmatic flow to continue.

**Comment by machawk1** [comment] 2021-06-28 16:49
Catching the TypeError and continuing the loop allows the WARC to be generated. Some logic needs to be added to resolve URIs like `hn.js` without any relative indicator. I believe using the native window.URL was for the basis of URIs like this, namely those that are relative (e.g., "`./hn.js`").

**Comment by machawk1** [comment] 2021-06-28 16:58
This has been resolved in c08bd3a and should be merged into the main branch shortly and hopefully push to the Chrome Dev Store soon after.

**Closed** 2021-06-28 17:08 UTC

**Comment by machawk1** [comment] 2021-06-28 17:23
@gjvnq  A new version of WARCreate (v0.2021.6.28) has been submitted for review to the Chrome Web Store. It should be available once it gets the approval of the admins there.

**Comment by gjvnq** [comment] 2021-06-28 22:14
Thanks!

Gabriel Queiroz
